language: cpp
compiler:
  - gcc
  - clang
script: make check
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="g++-4.8"; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - libcppunit-dev
